# -*- coding: utf-8 -*-
"""speech to text

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12tZ7QpwvX7jVsq88NiActcOUzSK0-PAT
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

!pip install moviepy
!pip install SpeechRecognition

import moviepy.editor as mp
import speech_recognition as sr
import os
def extract_speech_from_video(video_path):
    # Load the video clip
    clip = mp.VideoFileClip(video_path)

    # Extract audio from the video
    audio = clip.audio

    # Save the audio as a temporary WAV file
    audio_path = "temp_audio.wav"
    audio.write_audiofile(audio_path)

    # Use SpeechRecognition to transcribe the audio
    recognizer = sr.Recognizer()
    with sr.AudioFile(audio_path) as source:
        audio_data = recognizer.record(source)

    # Perform speech-to-text conversion
    try:
        text = recognizer.recognize_google(audio_data)
        print("Extracted speech: ", text)
    except sr.UnknownValueError:
        print("Speech recognition could not understand audio")
    except sr.RequestError as e:
        print("Could not request results from Google Speech Recognition service; {0}".format(e))

    # Clean up temporary audio file
    os.remove(audio_path)

# Example usage
video_path = "/content/drive/MyDrive/VideosSorted/Satellite/Video015-Scene-095.mp4"
extract_speech_from_video(video_path)