# -*- coding: utf-8 -*-
"""Text extract 2.0

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a9B1g1k5uq-NvuN_5FAtpStDZ2xJy0jP
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Install required libraries
!pip install moviepy easyocr

# Import necessary libraries
from moviepy.editor import VideoFileClip
import easyocr

# Function to extract text from video frames using easyocr
def extract_text_from_video_easyocr(video_path, language='en'):
    # Load the video clip
    clip = VideoFileClip(video_path)

    # Initialize easyocr reader
    reader = easyocr.Reader([language])

    # Extract text from each frame
    extracted_text = ""
    for frame in clip.iter_frames(fps=1):  # Change fps value as needed
        # Perform OCR on the frame
        results = reader.readtext(frame)

        # Extract text from results and append to the result
        for detection in results:
            text = detection[1]
            extracted_text += text + "\n"

    return extracted_text

# Define function to classify videos based on extracted text
def classify_video_by_text(extracted_text):
    # Define keywords or patterns for classification
    satellite_keywords = ['satellite', 'orbit', 'space']
    launch_keywords = ['launch', 'rocket', 'mission']
    rocket_keywords = ['rocket', 'spacecraft', 'orbit']

    # Initialize classification
    classification = []

    # Check for keywords and classify accordingly
    for keyword in satellite_keywords:
        if keyword in extracted_text.lower():
            classification.append('satellite')
            break

    for keyword in launch_keywords:
        if keyword in extracted_text.lower():
            classification.append('launch')
            break

    for keyword in rocket_keywords:
        if keyword in extracted_text.lower():
            classification.append('rocket')
            break

    return classification


# Specify the path to your video file
video_path = '/content/drive/MyDrive/VideosSorted/Satellite/Video015-Scene-095.mp4'

# Call the function to extract text from the video
result_text = extract_text_from_video_easyocr(video_path)

# Call the function to classify the video based on extracted text
video_classification = classify_video_by_text(result_text)

# Display the extracted text
print(result_text)

# Display the classification
print("Video classification:", video_classification)